import = ["/Users/gentashandi/.config/alacritty/themes/themes/catppuccin.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 4

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[scrolling]
# auto_scroll = false
history = 2000

[window]
decorations = "buttonless"
opacity = 1
option_as_alt = "Both"

[window.padding]
x = 8
y = 4
